### ISSUE TITLE
examples aren't working with latest version of mcplates

### ISSUE THREAD

**Issue by Swanson-Hysell** [ian-r-rose/bayesian_plate_reconstruction#2]
running the make file leads to this exception which is also an issue in invert_one_euler_pole.py and invert_two_euler_poles.py. Is this due to changes made while implementing the TPW  inversion?

```
Traceback (most recent call last):
  File "paleomagnetic_euler_pole.py", line 26, in <module>
    lon_lat = dummy_pole_position_fn(hidden_start_pole, a, hidden_euler_pole, hidden_euler_rate)
  File "/Users/Laurentia/0000_Github/mcplates/mcplates/apw_path.py", line 34, in pole_position
    raise Exception("Unexpected number of euler poles/changpoints: expected %i, got %i"%(n_euler_poles*3-1, len(args)))
Exception: Unexpected number of euler poles/changpoints: expected 2, got 0
```

**Comment by ian-r-rose** [comment]
Yes, that is probably the case. I should set up some tests and put them in CI so we can catch stuff like this.

**Comment by Swanson-Hysell** [comment]
That would be nice. Running the make file works as an initial test. 

Are you able to have a look at making the function compatible with both keweenawan_apw_path.py and invert_one_euler_pole.py/invert_two_euler_poles.py?

```
def generate_pole_position_fn(n_euler_poles, start_age):

        def pole_position(start, age, tpw_pole_angle, tpw_rate, *args):
            if len(args) != max( (n_euler_poles * 3 - 1), 0):
                raise Exception("Unexpected number of euler poles/changpoints: expected %i, got %i"%(n_euler_poles*3-1, len(args)))
```

**Comment by ian-r-rose** [comment]
Yes, I will work on updating these. My intention was to include a git submodule for the right version of mcplates so that it would always be in sync. I did this for the Keweenawan_Track repo, but clearly forgot to do that here.

**Comment by Swanson-Hysell** [comment]
Sounds good. However, for the sake of this manuscript, wouldn't it be best if all the examples can run out of the mcplates master rather than pointing to a previous version?

**Comment by ian-r-rose** [comment]
I think just the opposite. If we want this to be reproducible, we should specify *exactly* which version of the code is intended to be used. Adding a submodule allows us to specify the commit hash, not just the branch, which evolves in time.

**Comment by Swanson-Hysell** [comment]
Adding a submodule with a commit hash seems like a great way to make the code reproducible---you got me convinced in that regard.

It seems like it would be ideal for a current/slightly-updated version of mcplates that addresses this issue, to be used in this manuscript so that we can show an example utilizing the TPW functionality in addition to the synthetic inversions that are all using the same version of mcplates. From there, having that version of mcplates be a submodule in the repo that pulls in a specific commit makes sense.

**Comment by ian-r-rose** [comment]
I have made a PR that includes an mcplates submodule, and updated the figure scripts to point to it. Can you take a look to see if it works for you @Swanson-Hysell ?
